# Generated by Django 4.2.2 on 2024-04-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
                ("reading_texts", models.JSONField()),
                ("reading_puzzles", models.JSONField()),
                ("grammar_choose_correct", models.JSONField()),
                ("grammar_find_word", models.JSONField()),
            ],
        ),
    ]
