# Generated by Django 4.2.2 on 2024-04-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_data",
            name="grammar_choose_correct",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="grammar_find_word",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="reading_puzzles",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="reading_texts",
            field=models.JSONField(default=list),
        ),
    ]
