# Generated by Django 4.2.2 on 2024-04-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading_module",
            name="options",
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name="reading_module",
            name="questions",
            field=models.TextField(),
        ),
    ]
