# Generated by Django 4.2.2 on 2024-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_module", "0002_reading_module_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading_module",
            name="options",
            field=models.JSONField(default=list),
        ),
    ]
