# Generated by Django 4.2.2 on 2024-04-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reading_module", "0003_alter_reading_module_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading_puzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rus_word", models.TextField()),
                ("kaz_word", models.TextField()),
                ("shuffled_kaz_word", models.TextField()),
            ],
        ),
    ]
