# Generated by Django 4.2.2 on 2024-04-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grammmar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grammar_choose_correct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("word_to_replace", models.TextField()),
                ("options", models.JSONField(default=list)),
            ],
        ),
    ]
